apiVersion: v1
kind: Secret
metadata:
  name: conv-api-secret
type: Opaque
data:
  DATABASE_URL: cmFiYml0bXE6Ly9kZW1vOmRlbW9AcmFiYml0bXEtY2x1c3RlcmlwOjU2NzIvZGVtbw==
  AMQP_EXCHANGE: ZGVtby1leGNoYW5nZQ==        # "demo-exchange" (пример, подставь своё если нужно)
  AMQP_USER: ZGVtbw==                       # "demo"
  AMQP_PASSWORD: ZGVtbw==                   # "demo"
  AMQP_HOSTNAME: cmFiYml0bXEtY2x1c3Rlcmlw   # "rabbitmq-clusterip"
